name: CI Code Style Checks

on:
  pull_request:
    branches:
      - master

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        run: docker build -t recipe-nest-app -f docker/php/Dockerfile .

      - name: Run PHP CodeSniffer (phpcs)
        run: |
          docker run --rm recipe-nest-app vendor/bin/phpcs --standard=PSR12 src/

      - name: Run PHP Mess Detector (phpmd)
        run: |
          docker run --rm recipe-nest-app vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
